import { APCostConfig } from 'game-core';

export interface SkillInfo {
  id: string;
  name: string;
  cost: number | string;
  targetType: string;
  description: string;
  duration: string;
}

export interface VariantData {
  id: string;
  name: string;
  role: 'Executor' | 'Strategist' | 'Disruptor' | 'Warden' | 'Trickster';
  difficulty: number; // 1 to 5 stars
  description: string;
  artwork: string; // Emoji representing character
  passive: SkillInfo;
  skill1: SkillInfo;
  skill2: SkillInfo;
  ultimate: SkillInfo;
  image?: string;
  resourceLabel?: string;
  maxSkillsPerTurn?: number;
}

export const VARIANTS_LIST: VariantData[] = [
  {
    id: 'lightning',
    name: 'Lightning',
    role: 'Executor',
    difficulty: 3,
    description: 'Bậc thầy về điện năng và tốc độ, gây hiệu ứng làm choáng và quét sạch kẻ địch.',
    artwork: '⚡',
    resourceLabel: 'Stun traps',
    passive: {
      id: 'lightning_passive',
      name: 'Lightning Speed',
      cost: 'None',
      targetType: 'Passive',
      description: 'Mỗi khi quân địch đi vào ô bẫy choáng sẽ +2 AP.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'lightning_thunder_trap',
      name: 'Thunder Trap',
      cost: APCostConfig.lightning.lightning_skill_1,
      targetType: 'Empty Tile',
      description: 'Đặt một bẫy sét ẩn lên ô trống. Nếu kẻ địch đi vào sẽ bị làm choáng trong 2 vòng đấu.',
      duration: 'Permanent',
    },
    skill2: {
      id: 'lightning_electric_terrain',
      name: 'Electric Terrain',
      cost: APCostConfig.lightning.lightning_skill_2,
      targetType: 'Global Cell',
      description: 'Trong 5 vòng đấu tiếp theo, thời gian di chuyển mỗi lượt của 2 người chơi giảm còn 3 giây.',
      duration: '5 rounds',
    },
    ultimate: {
      id: 'lightning_raigeki',
      name: 'Raigeki',
      cost: APCostConfig.lightning.lightning_ultimate,
      targetType: 'Board-wide',
      description: 'Tiêu diệt tất cả quân địch đang mang hiệu ứng làm choáng (ngoại trừ Vua).',
      duration: 'Instant',
    }
  },
  {
    id: 'zombie',
    name: 'Zombie',
    role: 'Strategist',
    difficulty: 3,
    description: 'Lây lan dịch bệnh, biến binh lính địch thành xác sống và triệu hồi quái vật đông đảo.',
    artwork: '🧟',
    resourceLabel: 'Zombies count',
    passive: {
      id: 'zombie_passive',
      name: 'Zombie Infection',
      cost: 'None',
      targetType: 'Passive',
      description: 'Khi quân cờ Zombie ăn quân địch, quân bị ăn sẽ nhận hiệu ứng nhiễm độc Walker.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'zombie_infection',
      name: 'Infection',
      cost: APCostConfig.zombie.zombie_skill_1,
      targetType: 'Ally Piece',
      description: 'Chọn 1 quân cờ đồng minh và biến đổi nó thành một Zombie khát máu. Tối đa 5 Zombie tồn tại cùng lúc.',
      duration: 'Permanent',
    },
    skill2: {
      id: 'zombie_mutation',
      name: 'Mutation',
      cost: APCostConfig.zombie.zombie_skill_2,
      targetType: 'Walker Piece',
      description: 'Biến đổi 1 quân cờ Walker đang bị nhiễm độc thành Zombie thuộc quyền kiểm soát. Tối đa 5 Zombie tồn tại cùng lúc.',
      duration: 'Instant',
    },
    ultimate: {
      id: 'zombie_outbreak',
      name: 'Outbreak',
      cost: APCostConfig.zombie.zombie_ultimate,
      targetType: 'Graveyard',
      description: 'Hồi sinh 2 quân đồng minh bị chết gần nhất về lại vị trí chết ban đầu.',
      duration: 'Instant',
    }
  },
  {
    id: 'dynamite',
    name: 'Dynamite',
    role: 'Executor',
    difficulty: 4,
    description: 'Gài mìn, cài chất nổ kích nổ chuỗi phản ứng dây chuyền thổi bay toàn bộ quân địch.',
    artwork: '💣',
    resourceLabel: 'Active bombs',
    passive: {
      id: 'dynamite_passive',
      name: 'Explosives',
      cost: 'None',
      targetType: 'Passive',
      description: 'Mỗi khi kích hoạt Ultimate, cộng lại 2 AP. Khi bom được kích hoạt, chúng sẽ gây sát thương với diện tích 3x3 ô xung quanh.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'dynamite_live_charge',
      name: 'Live Charge',
      cost: APCostConfig.dynamite.dynamite_skill_1,
      targetType: 'Ally Piece',
      description: 'Gắn một khối thuốc nổ lên quân đồng minh. Quả bom tồn tại cho tới khi kích nổ hoặc quân bị chết.',
      duration: 'Permanent',
    },
    skill2: {
      id: 'dynamite_landmine',
      name: 'Landmine',
      cost: APCostConfig.dynamite.dynamite_skill_2,
      targetType: 'Empty Tile',
      description: 'Đặt một quả mìn ẩn trên ô trống. Kẻ địch bước vào sẽ nhận hiệu ứng Bomb.',
      duration: 'Permanent',
    },
    ultimate: {
      id: 'dynamite_detonation',
      name: 'Detonation',
      cost: APCostConfig.dynamite.dynamite_ultimate,
      targetType: 'Global',
      description: 'Kích nổ tất cả quân cờ đang mang hiệu ứng gắn thuốc nổ Bomb trên toàn bàn cờ.',
      duration: 'Instant',
    }
  },
  {
    id: 'magician',
    name: 'Magician',
    role: 'Trickster',
    difficulty: 4,
    description: 'Nhà ảo thuật gia hoán đổi các quân cờ và biến kẻ địch thành kẻ ngu ngốc',
    artwork: '🔮',
    resourceLabel: 'Spells active',
    passive: {
      id: 'magician_passive',
      name: 'Grand Illusions',
      cost: 'None',
      targetType: 'Passive',
      description: 'If 1 of the 2 swapped pieces is captured, the other gets Shield (ally) or Stun (enemy).',
      duration: '3 rounds',
    },
    skill1: {
      id: 'magician_swap_allies',
      name: 'Now You See Me',
      cost: APCostConfig.magician.magician_skill_1,
      targetType: '2 Ally Pieces',
      description: 'Hoán đổi vị trí lập tức giữa 2 quân đồng minh (trừ Vua). Khi hết 3 vòng đấu, hoán đổi ngược lại vị trí hiện tại của chúng.',
      duration: '3 rounds',
    },
    skill2: {
      id: 'magician_swap_movements',
      name: 'Misdirection',
      cost: APCostConfig.magician.magician_skill_2,
      targetType: '2 Enemy Pieces',
      description: 'Hoán đổi cách di chuyển giữa 2 quân địch (trừ Vua) trong 3 vòng đấu.',
      duration: '3 rounds',
    },
    ultimate: {
      id: 'magician_fool',
      name: 'Carnival of Fools',
      cost: APCostConfig.magician.magician_ultimate,
      targetType: 'Up to 5 Pieces',
      description: 'Áp dụng hiệu ứng Fool lên tối đa 5 quân bất kỳ (trừ Vua) buộc chúng tự động tiến lên 1 ô đầu lượt.',
      duration: '5 rounds',
    }
  },
  {
    id: 'guardian',
    name: 'Guardian',
    role: 'Warden',
    difficulty: 2,
    description: 'Tạo vùng bảo hộ, khiên chặn sát thương bảo vệ Vua và các quân cờ cốt lõi.',
    artwork: '🛡️',
    resourceLabel: 'Shields active',
    passive: {
      id: 'guardian_passive',
      name: 'Holy Aura',
      cost: 'None',
      targetType: 'Passive',
      description: `Khi mất đi 8 quân cờ, AP của Holy Shield sẽ giảm vĩnh viễn còn ${APCostConfig.guardian.guardian_skill_1_discount} AP.`,
      duration: 'Permanent',
    },
    skill1: {
      id: 'guardian_shield',
      name: 'Holy Shield',
      cost: APCostConfig.guardian.guardian_skill_1,
      targetType: 'Ally Piece',
      description: 'Tạo lớp khiên bảo vệ tuyệt đối cho 1 quân đồng minh trong vòng 2 vòng đấu.',
      duration: '2 rounds',
    },
    skill2: {
      id: 'guardian_sanctuary',
      name: 'Sanctuary',
      cost: APCostConfig.guardian.guardian_skill_2,
      targetType: '3x3 Area',
      description: 'Tạo 1 vùng bảo hộ 3x3. Địch ăn quân ta trong vùng này sẽ bị làm choáng 1 vòng đấu.',
      duration: '3 rounds',
    },
    ultimate: {
      id: 'guardian_ultimate',
      name: 'Divine Shield',
      cost: APCostConfig.guardian.guardian_ultimate,
      targetType: 'All Allies',
      description: 'Trao khiên bảo hộ thần thánh cho toàn bộ quân cờ đồng minh trên sân đấu trong 5 vòng đấu.',
      duration: '5 rounds',
    }
  },
  {
    id: 'requiem',
    name: 'Requiem',
    role: 'Disruptor',
    difficulty: 3,
    description: 'Thu hoạch linh hồn, nguyền rủa kẻ địch bằng Berserk và liên kết số phận các quân cờ.',
    artwork: '🎭',
    passive: {
      id: 'requiem_passive',
      name: 'Soul Harvest',
      cost: 'None',
      targetType: 'Passive',
      description: 'Mỗi khi ăn quân địch, nhận thêm +1 AP (ngoài phần thưởng thông thường).',
      duration: 'Permanent',
    },
    skill1: {
      id: 'requiem_soul_break',
      name: 'Soul Break',
      cost: APCostConfig.requiem.requiem_skill_1,
      targetType: 'Enemy Piece',
      description: 'Chọn 1 quân địch (ngoại trừ Vua) để nguyền rủa bằng Berserk. Nếu không ăn quân trong thời gian quy định, quân đó bị làm choáng.',
      duration: 'Permanent',
    },
    skill2: {
      id: 'requiem_thread_of_fate',
      name: 'Thread of Fate',
      cost: APCostConfig.requiem.requiem_skill_2,
      targetType: '1 Ally & 1 Enemy',
      description: 'Liên kết sinh mệnh giữa 1 quân đồng minh và 1 quân địch. Khi 1 quân chết, quân kia cũng chết theo.',
      duration: '3 rounds',
    },
    ultimate: {
      id: 'requiem_reapers_decree',
      name: "Reaper's Decree",
      cost: APCostConfig.requiem.requiem_ultimate,
      targetType: '2 Enemy Pieces',
      description: 'Gắn hiệu ứng liên kết số phận Fate lên 2 quân địch. Khi 1 quân chết, quân kia cũng chết theo.',
      duration: '5 rounds',
    }
  },
  {
    id: 'ruler',
    name: 'Ruler',
    role: 'Strategist',
    difficulty: 4,
    description: 'Thay đổi luật lệ bàn cờ trong vùng ảnh hưởng để ép đối thủ phải chơi theo ý mình.',
    artwork: '👑',
    resourceLabel: 'Active law',
    passive: {
      id: 'ruler_passive',
      name: 'Royal Decree',
      cost: 'None',
      targetType: 'Passive',
      description: 'Tạo vùng chiến trường 9x9 giữa bàn cờ áp dụng Giới luật 1: Chỉ quân giống nhau mới được ăn nhau.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'ruler_law2',
      name: 'Order of Hierarchy',
      cost: APCostConfig.ruler.ruler_skill_1,
      targetType: '9x9 Area',
      description: 'Đổi luật: Chỉ quân giá trị cao hơn mới được ăn quân giá trị thấp hơn.',
      duration: '3 rounds',
    },
    skill2: {
      id: 'ruler_law3',
      name: 'Decree of the Weak',
      cost: APCostConfig.ruler.ruler_skill_2,
      targetType: '9x9 Area',
      description: 'Đổi luật: Chỉ quân giá trị thấp hơn mới được ăn quân giá trị cao hơn.',
      duration: '3 rounds',
    },
    ultimate: {
      id: 'ruler_close_field',
      name: 'Absolute Domain',
      cost: APCostConfig.ruler.ruler_ultimate,
      targetType: '9x9 Area',
      description: 'Đóng chiến trường 9x9 trong 5 vòng đấu: quân ở ngoài không thể đi vào, quân ở trong không thể đi ra.',
      duration: '5 rounds',
    }
  },
  {
    id: 'kaze',
    name: 'Kazehime',
    role: 'Strategist',
    difficulty: 3,
    description: 'Sử dụng Phong Ấn Gió đẩy lùi đối thủ, đặt vùng bẫy gió repelling và gọi bão hủy diệt.',
    artwork: '💨',
    image: 'kazehime',
    resourceLabel: 'Wind Sigils',
    passive: {
      id: 'kaze_passive',
      name: 'Blessing of the Wind God',
      cost: 'None',
      targetType: 'Passive',
      description: 'Bắt đầu với 6 Phong Ấn Gió (Wind Sigils). Mỗi kỹ năng tiêu tốn 1 Phong Ấn Gió và hoàn lại sau khi bẫy biến mất.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'kaze_repel',
      name: 'Wind Reversal',
      cost: APCostConfig.kaze.kaze_skill_1,
      targetType: 'Cross Empty Area',
      description: 'Đặt hiệu ứng Repel lên vùng chữ thập 5 ô trống. Đẩy lùi quân địch đi vào về vị trí xuất phát, xóa bẫy và hoàn lại 1 Phong Ấn.',
      duration: 'Permanent',
    },
    skill2: {
      id: 'kaze_soulless',
      name: 'Illusory Wind',
      cost: APCostConfig.kaze.kaze_skill_2,
      targetType: 'X-shape Area',
      description: 'Đặt hiệu ứng Soulless lên vùng chữ X 5 ô trống. Kẻ địch đi vào bị cấm di chuyển 2 vòng đấu (Stun). Gỡ sớm nếu đồng minh dẫm vào ô xuất phát. Xóa bẫy và hoàn lại 1 Phong Ấn.',
      duration: '2 rounds',
    },
    ultimate: {
      id: 'kaze_storm',
      name: 'Eye of the Divine Storm',
      cost: APCostConfig.kaze.kaze_ultimate,
      targetType: '7x7 Area',
      description: 'Reset Phong Ấn Gió về 6, xóa mọi bẫy gió trên sân và tạo bão co cụm từ 7x7 đến 1 ô. Kẻ địch ở trong bão 2 lượt liên tiếp bị tiêu diệt (ngoại trừ Vua).',
      duration: '4 rounds',
    }
  },
  {
    id: 'nephalem',
    name: 'Nephalem',
    role: 'Disruptor',
    difficulty: 4,
    description: 'Nguyền rủa đối thủ bằng Berserk, xiềng xích stun cấm di chuyển và câm lặng kỹ năng của đối thủ.',
    artwork: '😈',
    passive: {
      id: 'nephalem_passive',
      name: 'Fallen Grace',
      cost: 'None',
      targetType: 'Passive',
      description: 'Mỗi khi có 3 quân đồng minh bị tiêu diệt, nhận ngay 4 AP.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'nephalem_judgment_chains',
      name: 'Judgment Chains',
      cost: APCostConfig.nephalem.nephalem_skill_1,
      targetType: 'Enemy Piece',
      description: 'Chọn 1 quân địch (ngoại trừ Vua) để làm choáng trong 3 vòng đấu.',
      duration: '3 rounds',
    },
    skill2: {
      id: 'nephalem_berserk_curse',
      name: 'Berserk Curse',
      cost: APCostConfig.nephalem.nephalem_skill_2,
      targetType: 'Enemy Piece',
      description: 'Chọn 1 quân địch và nguyền rủa nó bằng Berserk. Nếu trong 4 vòng đấu nó không ăn quân, nó bị làm choáng 6 lượt và xóa Berserk.',
      duration: 'Permanent',
    },
    ultimate: {
      id: 'nephalem_divine_silence',
      name: 'Divine Silence',
      cost: APCostConfig.nephalem.nephalem_ultimate,
      targetType: 'Opponent Player',
      description: 'Câm lặng đối phương trong 3 vòng đấu, chặn sử dụng toàn bộ kỹ năng kích hoạt.',
      duration: '3 rounds',
    }
  },
  {
    id: 'angel',
    name: 'Angel',
    role: 'Warden',
    difficulty: 3,
    description: 'Bảo hộ đồng minh, thanh tẩy nguyền rủa và trừng phạt tuyệt đối đối thủ bằng Judgment.',
    artwork: '👼',
    resourceLabel: 'Judgment active',
    passive: {
      id: 'angel_passive',
      name: 'Heavenly Grace',
      cost: 'None',
      targetType: 'Passive',
      description: 'Mỗi khi 1 quân đồng minh bị tiêu diệt (bất kỳ nguyên nhân nào) nhận ngay lập tức +2 AP.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'angel_holy_seal',
      name: 'Holy Seal',
      cost: APCostConfig.angel.angel_skill_1,
      targetType: 'Enemy Piece',
      description: 'Chọn 1 quân địch (ngoại trừ Vua) để làm choáng (Stun) trong 3 vòng đấu.',
      duration: '3 rounds',
    },
    skill2: {
      id: 'angel_blessing',
      name: 'Blessing',
      cost: APCostConfig.angel.angel_skill_2,
      targetType: 'Ally Piece',
      description: 'Chọn 1 quân đồng minh. Nếu quân đó có debuff, giải trừ toàn bộ debuff. Nếu không, ban Khiên Bảo Vệ trong 1 vòng đấu.',
      duration: 'Instant',
    },
    ultimate: {
      id: 'angel_divine_judgment',
      name: 'Divine Judgment',
      cost: APCostConfig.angel.angel_ultimate,
      targetType: 'Global',
      description: 'Kích hoạt Vòng Trừng Phạt trong 5 vòng đấu. Bất kỳ quân địch nào ăn quân trong thời gian này sẽ nhận Dấu Ấn Trừng Phạt. Hết 5 vòng đấu, tất cả quân mang dấu ấn bị tiêu diệt tuyệt đối.',
      duration: '5 rounds',
    }
  },
  {
    id: 'wizard',
    name: 'Wizard',
    role: 'Disruptor',
    difficulty: 4,
    description: 'Vị pháp sư thao túng chiến trường bằng ma pháp cổ xưa: hoán đổi vị trí kẻ địch, trói buộc tầm đi và hủy diệt kẻ mang dấu ấn Tử Vong.',
    artwork: '🧙',
    passive: {
      id: 'wizard_passive',
      name: 'Arcane Mastery',
      cost: 'None',
      targetType: 'Passive',
      description: 'Sau mỗi 2 lần dùng Skill 1 hoặc 2, AP của lần tiếp theo tăng 2. Cuối mỗi turn, quân địch bị chiếu nhận +1 Death Counter. Khi quân cờ mang Death Counter bị tiêu diệt, Wizard nhận lại AP tương ứng.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'wizard_arcane_swap',
      name: 'Arcane Swap',
      cost: APCostConfig.wizard.wizard_skill_1,
      targetType: '2 Enemy Pieces',
      description: 'Hoán đổi vị trí lập tức giữa 2 quân địch (trừ Vua). Khi hết hiệu lực, hoán đổi ngược lại. Nếu 1 quân bị tiêu diệt trước, hiệu ứng tự hủy.',
      duration: '2 rounds',
    },
    skill2: {
      id: 'wizard_arcane_bind',
      name: 'Arcane Bind',
      cost: APCostConfig.wizard.wizard_skill_2,
      targetType: '1 Enemy Piece',
      description: 'Trói buộc di chuyển của 1 quân địch trong vùng 5x5 quanh vị trí hiện tại của quân cờ đó.',
      duration: '3 rounds',
    },
    ultimate: {
      id: 'wizard_arcane_annihilation',
      name: 'Arcane Annihilation',
      cost: APCostConfig.wizard.wizard_ultimate,
      targetType: 'Marked Enemies',
      description: 'Tự động tiêu diệt toàn bộ quân địch đạt tối đa 6 dấu ấn Tử Vong. AP cost giảm dần theo số lượng mục tiêu bị tiêu diệt (1 mục tiêu: 14 AP, 2-3: 12 AP, 4-5: 10 AP, 6+: 8 AP).',
      duration: 'Instant',
    }
  },
  {
    id: 'devil',
    name: 'Devil',
    role: 'Executor',
    difficulty: 5,
    description: 'Bậc thầy về giao kèo quỷ dữ, đánh phí nước đi và hiến tế linh hồn đổi lấy sức mạnh vô song.',
    artwork: '😈',
    passive: {
      id: 'devil_passive',
      name: 'Infernal Pact',
      cost: 'None',
      targetType: 'Passive',
      description: 'Mỗi khi bắt đầu lượt đi của Devil player, tự động nhận thêm +1 AP.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'devil_eye_skill',
      name: "Devil's Eye",
      cost: APCostConfig.devil.devil_skill_1,
      targetType: 'Ally Piece',
      description: "Áp đặt Devil's Eye lên 1 quân đồng minh (trừ Vua). Nếu quân địch chiếu vào quân đó sẽ bị Làm Choáng 6 lượt và xóa Devil's Eye.",
      duration: '2 rounds',
    },
    skill2: {
      id: 'wrath_curse_skill',
      name: 'Wrath Curse',
      cost: APCostConfig.devil.devil_skill_2,
      targetType: 'Enemy Piece',
      description: 'Nguyền rủa 1 quân địch (trừ Vua) bằng hiệu ứng Berserk. Nếu quân đó không ăn quân trong 4 lượt sẽ bị câm lặng/stun 3 lượt.',
      duration: 'Permanent',
    },
    ultimate: {
      id: 'hellish_toll_skill',
      name: 'Hellish Toll',
      cost: APCostConfig.devil.devil_ultimate,
      targetType: 'Global',
      description: "Kích hoạt Devil's Toll trong 6 vòng đấu. Mọi nước đi không ăn quân của cả 2 bên đều tốn AP theo loại quân. Nếu thiếu AP phải chọn hiến tế 1 quân.",
      duration: '6 rounds',
    }
  },
  {
    id: 'cherubim',
    name: 'Cherubim',
    role: 'Strategist',
    difficulty: 4,
    description: 'Bậc thầy sử dụng song song kỹ năng, tiến hóa quân Tốt thành Hậu siêu việt và thanh tẩy chiến trường bằng Totem hộ mệnh.',
    artwork: '👼',
    maxSkillsPerTurn: 2,
    passive: {
      id: 'cherubim_passive',
      name: 'Dual Casting',
      cost: 'None',
      targetType: 'Passive',
      description: 'Cho phép dùng tối đa 2 kỹ năng KHÁC NHAU trong cùng một lượt. Không thể sử dụng cùng một kỹ năng quá một lần mỗi lượt.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'cherubim_ascend',
      name: 'Ascend',
      cost: APCostConfig.cherubim.cherubim_skill_1,
      targetType: 'Ally Pawn',
      description: 'Chọn 1 quân Tốt đồng minh để ban hiệu ứng Thăng Hoa (Ascend). Sau 5 vòng đấu, quân Tốt sẵn sàng tiến hóa.',
      duration: 'Permanent',
    },
    skill2: {
      id: 'cherubim_fountain_of_youth',
      name: 'Fountain of Youth',
      cost: APCostConfig.cherubim.cherubim_skill_2,
      targetType: 'Empty Cell',
      description: 'Triệu hồi 1 Totem hộ mệnh tồn tại trong 3 vòng đấu. Mỗi lượt, Totem xóa sạch cell effects trong vùng 3x3 quanh nó, đồng thời thanh tẩy các quân cờ lân cận (loại bỏ debuff đối với đồng minh, xóa sạch mọi hiệu ứng đối với kẻ địch, ngoại trừ Thăng Hoa).',
      duration: '3 rounds',
    },
    ultimate: {
      id: 'cherubim_divine_ascension',
      name: 'Divine Ascension',
      cost: APCostConfig.cherubim.cherubim_ultimate,
      targetType: 'Ready Pawns / Cell',
      description: 'Trường hợp A: Tiến hóa vĩnh viễn toàn bộ quân Tốt đồng minh đã hoàn thành Thăng Hoa thành Hậu thật. Trường hợp B (nếu không có quân nào đủ điều kiện): Triệu hồi 1 quân Tốt bình thường tại ô trống do bạn chọn nằm ở nửa sân của mình.',
      duration: 'Instant',
    }
  },
  {
    id: 'thunder_dragon',
    name: 'Thunder Dragon',
    role: 'Executor',
    difficulty: 4,
    description: 'Rồng sấm sét tích điện từ mỗi đòn choáng, điện hóa đồng minh và xóa sổ kẻ địch bằng cơn thịnh nộ sấm sét.',
    artwork: '🐉',
    resourceLabel: 'Stunned enemies',
    passive: {
      id: 'thunder_dragon_passive',
      name: 'Static Charge',
      cost: 'None',
      targetType: 'Passive',
      description: 'Mỗi khi đến lượt của bạn, nhận +1 AP cho mỗi quân địch đang mang hiệu ứng Stun trên bàn cờ.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'thunder_dragon_dragons_scale',
      name: "Dragon's Scale",
      cost: APCostConfig.thunder_dragon.thunder_dragon_skill_1,
      targetType: 'Ally Piece',
      description: 'Trao cho 1 quân đồng minh hiệu ứng Electric trong 1 vòng đấu. Khi quân địch ăn quân mang Electric, quân địch đó bị Stun 2 vòng đấu.',
      duration: '1 round',
    },
    skill2: {
      id: 'thunder_dragon_thunder_fang',
      name: 'Thunder Fang',
      cost: APCostConfig.thunder_dragon.thunder_dragon_skill_2,
      targetType: 'Ally Piece',
      description: 'Trao cho 1 quân đồng minh hiệu ứng Thunder Fang đến hết lượt hiện tại. Quân đó có thể ăn địch từ xa mà không di chuyển. Khi tiêu diệt địch, ô đó trở thành bẫy sét Stun 2 vòng đấu.',
      duration: 'Current turn',
    },
    ultimate: {
      id: 'thunder_dragon_dragons_wrath',
      name: "Dragon's Wrath",
      cost: APCostConfig.thunder_dragon.thunder_dragon_ultimate,
      targetType: 'Directional 3×10 Zone',
      description: 'Chọn 1 trong 8 ô kề Vua để xác định hướng. Tạo vùng ảnh hưởng 3×10 theo hướng đó: Stun toàn bộ địch trong vùng, sau đó tiêu diệt mọi địch đang bị Stun (kể cả Vua địch).',
      duration: 'Instant',
    }
  },
  {
    id: 'earth',
    name: 'Earth',
    role: 'Warden',
    difficulty: 3,
    description: 'Vũ trụ kiên cố của Đất: Kiến tạo những ngọn núi hùng vĩ chắn tầm nhìn, dịch chuyển địa hình dồn ép quân địch và lưu đày mục tiêu xuống lòng đất.',
    artwork: '⛰️',
    passive: {
      id: 'earth_passive',
      name: 'Ground Dominion',
      cost: 'None',
      targetType: 'Passive',
      description: 'Mỗi ngọn núi của bạn trên bàn cờ giảm 1 AP cost cho Shifting Peaks (tối đa giảm còn 3 AP). AP cost tính cố định khi bắt đầu turn.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'earth_raise_mountain',
      name: 'Raise the Mountain',
      cost: APCostConfig.earth.earth_skill_1,
      targetType: 'Empty Cell',
      description: 'Kiến tạo 1 ngọn núi tại ô trống tồn tại trong 5 vòng đấu. Núi chặn tầm nhìn, di chuyển và tấn công của cả hai bên.',
      duration: '5 rounds',
    },
    skill2: {
      id: 'earth_shifting_peaks',
      name: 'Shifting Peaks',
      cost: `${APCostConfig.earth.earth_skill_2 - 3}-${APCostConfig.earth.earth_skill_2}`,
      targetType: 'Mountain & Empty Cell',
      description: 'Dịch chuyển một ngọn núi theo đường đi của Hậu, dồn ép quân địch trên đường đi đến khi gặp vật cản. Spawns núi mới ở nguồn.',
      duration: 'Instant',
    },
    ultimate: {
      id: 'earth_earth_burst',
      name: 'Earth-Burst Heavenly Star',
      cost: APCostConfig.earth.earth_ultimate,
      targetType: 'Enemy Piece',
      description: 'Yêu cầu >= 3 núi. Tiêu diệt tất cả núi đồng minh, lưu đày 1 quân địch (trừ Vua) xuống lòng đất trong N vòng đấu (N là số núi bị xóa). Hết hạn sẽ hoàn trả quân địch về ô cũ.',
      duration: 'N rounds',
    }
  },
  {
    id: 'cannibal',
    name: 'Cannibal',
    role: 'Trickster',
    difficulty: 4,
    description: 'Một kẻ thống trị tăm tối, phàm ăn, nuốt chửng đồng minh của mình để có được khả năng di chuyển và AP.',
    artwork: '👑',
    resourceLabel: 'Devoured state',
    passive: {
      id: 'cannibal_passive',
      name: 'Cannibal King',
      cost: 'None',
      targetType: 'Passive',
      description: 'Vua có thể ăn quân đồng minh. Khi ăn quân đồng minh, người chơi nhận cả AP capture + loss của quân đó, địch không nhận gì. Khi ăn bất kỳ quân nào, Vua sao chép nước đi của quân đó.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'cannibal_royal_guard',
      name: 'Royal Guard',
      cost: APCostConfig.cannibal.cannibal_skill_1,
      targetType: 'Ally King',
      description: 'Áp dụng Khiên Bảo Vệ lên Vua đồng minh trong 2 vòng đấu.',
      duration: '2 rounds',
    },
    skill2: {
      id: 'cannibal_devour',
      name: 'Devour',
      cost: APCostConfig.cannibal.cannibal_skill_2,
      targetType: 'Ally Piece',
      description: 'Áp dụng hiệu ứng Devour lên Vua trong 3 vòng đấu giúp Vua di chuyển như quân cờ đồng minh được chọn, đồng thời làm choáng quân cờ đó trong 3 vòng đấu.',
      duration: '3 rounds',
    },
    ultimate: {
      id: 'cannibal_apex_predator',
      name: 'Apex Predator',
      cost: APCostConfig.cannibal.cannibal_ultimate,
      targetType: 'Global',
      description: 'Trong 10 vòng đấu tiếp theo, Vua di chuyển như Hậu + Mã kết hợp. Cứ ăn 2 quân bất kỳ sẽ nhận thêm Khiên Bảo Vệ trong 1 vòng đấu.',
      duration: '10 rounds',
    }
  },
  {
    id: 'phantom',
    name: 'Phantom',
    role: 'Trickster',
    difficulty: 4,
    description: 'Băng qua các chướng ngại vật với hiệu ứng Ghost, sở hữu quân địch để biến hình vĩnh viễn và ẩn mình dưới bóng tối của Spirit Walk.',
    artwork: '👻',
    passive: {
      id: 'phantom_passive',
      name: 'Ghost Inheritance',
      cost: 'None',
      targetType: 'Passive',
      description: 'Khi quân đồng minh có Ghost bị tiêu diệt, lập tức tìm quân đồng minh gần nhất để trao Ghost trong 1 vòng đấu.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'phantom_haunt_skill',
      name: 'Haunt',
      cost: APCostConfig.phantom.phantom_skill_1,
      targetType: 'Ally Piece',
      description: 'Trao hiệu ứng Ghost cho 1 quân đồng minh (ngoại trừ Vua/Mã) trong 3 vòng đấu. Nếu tàng hình đang hoạt động, quân này cũng được ẩn mình.',
      duration: '3 rounds',
    },
    skill2: {
      id: 'phantom_possession_skill',
      name: 'Possession',
      cost: APCostConfig.phantom.phantom_skill_2,
      targetType: 'Global',
      description: 'Trong lượt này, bất kỳ quân đồng minh mang Ghost nào ăn quân địch sẽ vĩnh viễn biến đổi thành quân bị ăn đó và xóa Ghost.',
      duration: 'Current turn',
    },
    ultimate: {
      id: 'phantom_spirit_walk_skill',
      name: 'Spirit Walk',
      cost: APCostConfig.phantom.phantom_ultimate,
      targetType: 'All Allied Ghost Pieces',
      description: 'Khởi động tàng hình, reset thời gian tất cả Ghost đồng minh về 5 vòng đấu và cho phép sử dụng 3 lần Haunt miễn phí.',
      duration: 'Permanent',
    }
  },
  {
    id: 'time',
    name: 'Time',
    role: 'Strategist',
    difficulty: 4,
    description: 'Bậc thầy kiểm soát dòng thời gian, quay ngược trạng thái bàn cờ, dự đoán nước đi và đóng băng đối thủ.',
    artwork: '⏳',
    resourceLabel: 'Ultimate usage',
    passive: {
      id: 'time_passive',
      name: 'Temporal Burden',
      cost: 'None',
      targetType: 'Passive',
      description: 'Mỗi lần dùng Ultimate, AP cost của Ultimate tăng dần: 6 AP -> 9 AP -> 15 AP.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'time_rewind',
      name: 'Rewind',
      cost: APCostConfig.time.time_skill_1,
      targetType: 'Global',
      description: 'Đưa vị trí tất cả các quân cờ còn sống về vị trí của chúng ở 1 round trước (2 turns trước). Các quân cờ sinh ra sau snapshot giữ nguyên vị trí.',
      duration: 'Instant',
    },
    skill2: {
      id: 'time_prediction',
      name: 'Future Prediction',
      cost: APCostConfig.time.time_skill_2,
      targetType: 'Enemy & Tile',
      description: 'Chọn 1 quân địch và 1 ô dự đoán di chuyển. Nếu trong lượt tới chúng di chuyển/ăn quân vào ô đó, chúng bị làm choáng (Stun) trong 4 vòng đấu.',
      duration: '1 round',
    },
    ultimate: {
      id: 'time_time_freeze',
      name: 'Time Collapse',
      cost: APCostConfig.time.time_ultimate.join('/'),
      targetType: 'Choice',
      description: 'Chọn 1 trong 2 quyền năng: A) Grand Rewind - Quay ngược bàn cờ 5 rounds trước. B) Time Freeze - Đóng băng đối thủ trong 6 rounds.',
      duration: 'Instant',
    }
  },
  {
    id: 'predator',
    name: 'Predator',
    role: 'Executor',
    difficulty: 4,
    description: 'Kẻ săn mồi tối thượng ẩn mình trong bóng tối, thu thập AP khi tiêu diệt Tốt địch, đột biến tiến hóa Tốt đồng minh và đặt bẫy Stun kẻ địch từ bóng tối.',
    artwork: '🦁',
    passive: {
      id: 'predator_passive',
      name: "Hunter's Instinct",
      cost: 'None',
      targetType: 'Passive',
      description: 'Mỗi khi quân đồng minh capture một quân Tốt địch chưa tiến hóa, nhận ngay +2 AP.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'predator_evolution_spore',
      name: 'Evolution Spore',
      cost: APCostConfig.predator.predator_skill_1,
      targetType: 'Ally Pawn',
      description: 'Ký sinh bào tử tiến hóa lên 1 quân Tốt đồng minh (vô hiệu hóa tự động phong cấp). Khi quân này capture bất kỳ quân nào: nếu < 2 rounds sẽ mất bào tử; >= 2 rounds tiến hóa thành Mã; >= 3 rounds thành Tượng; >= 4 rounds thành Xe; >= 5 rounds thành Hậu.',
      duration: 'Permanent',
    },
    skill2: {
      id: 'predator_shadow_prowl',
      name: 'Shadow Prowl',
      cost: APCostConfig.predator.predator_skill_2,
      targetType: 'Empty Tile',
      description: 'Đặt bẫy gió Soulless lên 1 ô trống nằm trong tầm tấn công của đồng minh. Địch đi vào sẽ bị làm choáng (Stun) trong 2 vòng đấu. Có thể giải cứu nếu đồng minh của kẻ bị Stun đi vào ô xuất phát.',
      duration: '2 rounds',
    },
    ultimate: {
      id: 'predator_apex_camouflage',
      name: 'Apex Camouflage',
      cost: APCostConfig.predator.predator_ultimate,
      targetType: 'Global',
      description: 'Tàng hình toàn bộ quân đồng minh (ngoại trừ Vua) khỏi tầm nhìn của kẻ địch trong 5 vòng đấu. Lộ diện nếu đứng cạnh kẻ địch vào cuối lượt hoặc khi thực hiện hành động capture.',
      duration: '5 rounds',
    }
  },
  {
    id: 'verdant_dragon',
    name: 'Verdant Dragon',
    role: 'Strategist',
    difficulty: 4,
    description: 'Bảo hộ đồng minh tránh tổn thất AP, trừng phạt chuyển động địch bằng Dragon\'s Gaze và biến đổi Ultimate thành Dragon\'s Wrath khi đạt 100 Counter.',
    artwork: '🐉',
    resourceLabel: 'Dragon Counter',
    passive: {
      id: 'verdant_dragon_passive',
      name: 'Dragon Counter',
      cost: 'None',
      targetType: 'Passive',
      description: 'Mỗi khi nhận AP từ bất kỳ nguồn nào sẽ tăng Dragon Counter tương ứng. Địch dùng skill cho bạn +3 AP ngay lập tức.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'verdant_dragon_verdant_shelter',
      name: 'Verdant Shelter',
      cost: APCostConfig.verdant_dragon.verdant_dragon_skill_1,
      targetType: 'Ally Piece',
      description: 'Ban Shelter cho 1 quân đồng minh trong 4 vòng đấu. Khi bị ăn hoặc bị tiêu diệt, kẻ địch chỉ nhận một nửa số AP capture.',
      duration: '4 rounds',
    },
    skill2: {
      id: 'verdant_dragon_dragons_gaze',
      name: "Dragon's Gaze",
      cost: APCostConfig.verdant_dragon.verdant_dragon_skill_2,
      targetType: 'Enemy Piece',
      description: 'Áp đặt Ánh Nhìn Lục Bảo lên 1 quân địch in 2 vòng đấu. Nếu nó di chuyển/ăn quân, bạn nhận +2 AP và xóa Gaze. Nếu không di chuyển, đối phương bị trừ 2 AP khi hết hiệu lực.',
      duration: '2 rounds',
    },
    ultimate: {
      id: 'verdant_dragon_ultimate',
      name: 'Emerald Domain',
      cost: APCostConfig.verdant_dragon.verdant_dragon_ultimate,
      targetType: '3 Enemy Pieces',
      description: 'Làm choáng (Stun) 3 quân địch trong 3 vòng đấu và tạo Emerald Domain tăng AP cost kỹ năng đối thủ thêm 1. Mỗi khi đối thủ dùng kỹ năng, bạn nhận lại một nửa AP của họ.',
      duration: '3 rounds',
    }
  },
  {
    id: 'lord',
    name: 'Lord',
    role: 'Strategist',
    difficulty: 3,
    description: 'Chiến thuật gia kiêu hãnh thống trị bàn cờ bằng cách điều khiển quân lực và ra lệnh cấm tuyệt đối đối phương.',
    artwork: '👑',
    passive: {
      id: 'lord_passive',
      name: 'Overwhelm',
      cost: 'None',
      targetType: 'Passive',
      description: 'Sau mỗi 5 rounds, nhận AP bằng chênh lệch số quân giữa hai bên (bao gồm cả King và quân triệu hồi).',
      duration: 'Permanent',
    },
    skill1: {
      id: 'lord_vanguard_command',
      name: 'Vanguard Command',
      cost: APCostConfig.lord.lord_skill_1,
      targetType: 'Ally Piece',
      description: 'Chọn 1 quân đồng minh. Tiêu diệt quân đầu tiên gặp trên đường trong phạm vi 3 ô thẳng phía trước (không giết King, dừng kiểm tra nếu gặp King trước), chỉ cast được nếu có ít nhất một quân địch trong phạm vi 3 ô.',
      duration: 'Instant',
    },
    skill2: {
      id: 'lord_reinforcements',
      name: 'Reinforcements',
      cost: APCostConfig.lord.lord_skill_2,
      targetType: 'Empty Tile',
      description: 'Triệu hồi tối đa 2 Pawn đồng minh lên ô trống ở nửa sân nhà. Pawn không được promotion. Thời lượng tồn tại phụ thuộc vào tương quan quân lực.',
      duration: 'Varies',
    },
    ultimate: {
      id: 'lord_iron_authority',
      name: 'Iron Authority',
      cost: APCostConfig.lord.lord_ultimate,
      targetType: 'Opponent Player',
      description: 'Cấm đối thủ sử dụng Skill 1 và Skill 2. Thời lượng là 3 rounds nếu quân ta <= quân địch, hoặc 5 rounds nếu quân ta > quân địch. Dùng lại refresh thời lượng.',
      duration: '3 or 5 rounds',
    }
  },
  {
    id: 'dragon_sentinel',
    name: 'Dragon Sentinel',
    role: 'Warden',
    difficulty: 4,
    description: 'Vệ binh rồng mạnh mẽ bảo vệ đồng minh bằng khiên chặn, đẩy lùi kẻ địch bằng sóng chấn động và khai hỏa luồng sáng hủy diệt khi vận sức thành công.',
    artwork: '🐉',
    passive: {
      id: 'dragon_sentinel_passive',
      name: 'Dragon Guard',
      cost: 'None',
      targetType: 'Passive',
      description: 'Sau mỗi 2 vòng đấu, quân đồng minh gần Vua nhất (trừ Vua) sẽ nhận Khiên bảo vệ trong 1 vòng đấu.',
      duration: '1 round',
    },
    skill1: {
      id: 'dragon_sentinel_subterranean_escape',
      name: 'Subterranean Escape',
      cost: APCostConfig.dragon_sentinel.dragon_sentinel_skill_1,
      targetType: 'Ally Piece',
      description: 'Chọn 1 quân đồng minh (trừ Vua). Trong 2 vòng đấu tiếp theo, nếu quân này bị ăn, nó sẽ chui xuống đất biến mất khỏi bàn cờ trong 2 vòng đấu rồi chui lên tiêu diệt quân tại vị trí đó.',
      duration: '2 rounds',
    },
    skill2: {
      id: 'dragon_sentinel_shockwave',
      name: 'Shockwave',
      cost: APCostConfig.dragon_sentinel.dragon_sentinel_skill_2,
      targetType: 'Ally Piece',
      description: 'Chọn 1 quân đồng minh làm tâm chấn. Đẩy toàn bộ quân địch trong phạm vi 3x3 ra xa 1 ô. Nếu ô bị đẩy bị cản thì giữ nguyên vị trí.',
      duration: 'Instant',
    },
    ultimate: {
      id: 'dragon_sentinel_dragons_roar',
      name: "Dragon's Roar",
      cost: APCostConfig.dragon_sentinel.dragon_sentinel_ultimate,
      targetType: 'Orthogonal Tile',
      description: 'Vua vận sức trong 5 vòng đấu (giảm 1 vòng mỗi khi quân đồng minh hiến tế/chết). Trong khi vận và duy trì, Vua bị khóa di chuyển. Khi hoàn thành, chiếu luồng sáng 15x1 hủy diệt toàn bộ kẻ địch trên đường thẳng đó và duy trì vùng hủy diệt trong 5 vòng đấu tiếp theo.',
      duration: '5 rounds',
    }
  },
  {
    id: 'turtle',
    name: 'Turtle',
    role: 'Warden',
    difficulty: 3,
    description: 'Một pháo đài phòng thủ kiên cố, ban Aegis miễn nhiễm hiệu ứng, trừng phạt kẻ địch bằng Bind và chuyển giao hiệu ứng giữa các quân cờ.',
    artwork: '🐢',
    passive: {
      id: 'turtle_passive',
      name: "Turtle's Retaliation",
      cost: 'None',
      targetType: 'Passive',
      description: 'Khi quân địch ăn quân đồng minh đang có hiệu ứng Aegis, quân địch đó sẽ bị Bind (trói chân) trong 2 vòng đấu.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'turtle_transference',
      name: 'Transference',
      cost: APCostConfig.turtle.turtle_skill_1,
      targetType: 'Source -> Effect -> Destination',
      description: 'Chuyển giao buff từ kẻ địch sang đồng minh, hoặc debuff từ đồng minh sang kẻ địch. Chỉ áp dụng với Stun, Shield, Blessing, Electron, Ghost.',
      duration: 'Instant',
    },
    skill2: {
      id: 'turtle_aegis_blessing',
      name: 'Aegis Blessing',
      cost: APCostConfig.turtle.turtle_skill_2,
      targetType: 'Ally Piece',
      description: 'Ban Aegis cho 1 quân đồng minh (ngoại trừ Vua) trong 2 vòng đấu, giúp quân cờ miễn nhiễm mọi hiệu ứng từ đối thủ và không bị chọn làm mục tiêu bởi kỹ năng đối thủ.',
      duration: '2 rounds',
    },
    ultimate: {
      id: 'turtle_great_sanctuary',
      name: 'Great Sanctuary',
      cost: APCostConfig.turtle.turtle_ultimate,
      targetType: 'All Allies',
      description: 'Ban Aegis cho toàn bộ quân đồng minh (ngoại trừ Tốt và Vua) trong 5 vòng đấu.',
      duration: '5 rounds',
    }
  },
  {
    id: 'phoenix',
    name: 'Phoenix',
    role: 'Executor',
    difficulty: 4,
    description: 'Một phượng hoàng kiêu hãnh hồi sinh từ đống tro tàn, thiêu đốt chiến trường và phong tỏa kỹ năng đối phương.',
    artwork: '🔥',
    passive: {
      id: 'phoenix_passive',
      name: 'Rebirth',
      cost: 'None',
      targetType: 'Passive',
      description: 'Khi Vua bị ăn lần đầu tiên, xóa toàn bộ đồng minh hiện tại, hồi sinh King+Rook+2 Bishop+Knight tại start, đồng thời dịch chuyển đối thủ gốc về start và khóa kỹ năng Phoenix vĩnh viễn.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'phoenix_ashes',
      name: 'Ashes of Reanimation',
      cost: APCostConfig.phoenix.phoenix_skill_1,
      targetType: 'Fallen Ally & Empty Cell',
      description: 'Hồi sinh 1 quân đồng minh trong graveyard đặt lên ô trống ở nửa sân nhà trong 4 vòng đấu (AP: Tốt 3, Mã/Tượng 5, Xe 7, Hậu 10).',
      duration: '4 rounds',
    },
    skill2: {
      id: 'phoenix_solar_flare',
      name: 'Solar Flare',
      cost: APCostConfig.phoenix.phoenix_skill_2,
      targetType: 'Enemy Piece',
      description: 'Làm choáng (Stun) 1 quân địch bị >= 2 Bishop đồng minh cùng chiếu trong 2 vòng đấu, đồng thời gây Flame vùng 5x5 quanh mục tiêu cấm di chuyển trong 4 vòng đấu.',
      duration: '2 rounds',
    },
    ultimate: {
      id: 'phoenix_supernova',
      name: 'Supernova',
      cost: APCostConfig.phoenix.phoenix_ultimate,
      targetType: 'Cell',
      description: 'Chọn vùng 7x7 hiển thị cảnh báo. Kích nổ tiêu diệt toàn bộ quân cờ bên trong (trừ Vua) sau 3 vòng đấu (6 turns).',
      duration: '3 rounds',
    }
  },
  {
    id: 'space',
    name: 'Space',
    role: 'Strategist',
    difficulty: 4,
    description: 'Thao túng không gian bằng cổng dịch chuyển Dimension Link, hoán đổi Spatial Shift và tạo ô Outworld bảo hộ.',
    artwork: '🌌',
    passive: {
      id: 'space_passive',
      name: 'Spatial Outworld',
      cost: 'None',
      targetType: 'Passive',
      description: 'Mỗi khi dùng Skill 1 hoặc 2, tạo ô Outworld tại các cổng Dimension mới/hoán đổi trong 2 vòng đấu. Chỉ quân Space đi qua được, quân địch bị cấm đi vào/đi qua.',
      duration: '2 rounds',
    },
    skill1: {
      id: 'space_dimension_link',
      name: 'Dimension Link',
      cost: APCostConfig.space.space_skill_1,
      targetType: '2 Empty Cells',
      description: 'Đặt 1 cổng lẻ ở sân nhà và 1 cổng chẵn ở sân đối phương. Quân địch đi qua/đáp vào cổng lẻ sẽ bị dịch chuyển sang cổng chẵn tương ứng và hủy cặp cổng. Quân ta đứng im trên cổng lẻ 1 vòng đấu cũng được dịch chuyển sang cổng chẵn.',
      duration: 'Permanent',
    },
    skill2: {
      id: 'space_spatial_shift',
      name: 'Spatial Shift',
      cost: APCostConfig.space.space_skill_2,
      targetType: '1 Active Portal',
      description: 'Chọn 1 cổng để hoán đổi cặp cổng bằng cách giữ nguyên hàng, đổi cột. Quân địch đang đứng ở ô đích sẽ bị tiêu diệt lập tức.',
      duration: 'Instant',
    },
    ultimate: {
      id: 'space_cosmic_void',
      name: 'Cosmic Void',
      cost: APCostConfig.space.space_ultimate,
      targetType: 'Global',
      description: 'Trong 10 vòng đấu tiếp theo, mọi pha ăn quân địch của người chơi Space đều tạo ô Outworld tại vị trí bị ăn. Toàn bộ các ô Outworld này cùng hết hạn sau 10 vòng đấu.',
      duration: '10 rounds',
    }
  },
  {
    id: 'puppet',
    name: 'Puppet',
    role: 'Strategist',
    difficulty: 4,
    description: 'Thao túng tâm lý và kiểm soát cục diện: Chia sẻ sát thương qua Voodoo Doll, giăng bẫy dây thối chí và chiếm đoạt thể xác đối phương.',
    artwork: '🪡',
    passive: {
      id: 'puppet_passive',
      name: 'Puppet Strings',
      cost: 'None',
      targetType: 'Passive',
      description: 'Quân địch bị tác động bởi kỹ năng của Puppet sẽ bị Bind trong 2 vòng đấu (bắt đầu tính SAU KHI hiệu ứng của kỹ năng đó kết thúc hoàn toàn).',
      duration: '2 rounds',
    },
    skill1: {
      id: 'puppet_soul_binding',
      name: 'Soul Binding',
      cost: APCostConfig.puppet.puppet_skill_1,
      targetType: '1 Ally Main & 1 Ally Voodoo',
      description: 'Chọn 1 quân đồng minh làm Main, 1 quân khác làm Voodoo. Khi Main bị tiêu diệt, sát thương chuyển sang Voodoo khiến Voodoo chết thay. Chỉ tồn tại duy nhất 1 cặp cùng lúc.',
      duration: 'Permanent',
    },
    skill2: {
      id: 'puppet_strings',
      name: 'Puppet Strings',
      cost: APCostConfig.puppet.puppet_skill_2,
      targetType: 'Empty Cell',
      description: 'Đặt bẫy tơ rối lên 1 ô trống. Quân địch dẫm phải bị Stun 2 vòng đấu và không thể thực hiện capture ở nước đi kế tiếp.',
      duration: 'Permanent',
    },
    ultimate: {
      id: 'puppet_master',
      name: 'Puppet Master',
      cost: `${APCostConfig.puppet.puppet_ultimate}-${APCostConfig.puppet.puppet_table.Queen}`,
      targetType: 'Enemy Piece',
      description: 'Chiếm quyền điều khiển 1 quân địch (trừ Vua) trong 7 vòng đấu (AP: Tốt 2, Mã/Tượng 5, Xe 8, Hậu 11). 2 lượt đầu pre-control (không được capture), 5 lượt sau full-control. Quân cờ không được phong cấp.',
      duration: '7 rounds',
    }
  },
  {
    id: 'pirate',
    name: 'Pirate',
    role: 'Executor',
    difficulty: 4,
    description: 'Thuyền trưởng cướp biển liều lĩnh: sẵn sàng nợ AP để kích hoạt kỹ năng, đánh cược chiến thuật và nã đại bác tiêu diệt kẻ thù.',
    artwork: '🏴‍☠️',
    passive: {
      id: 'pirate_passive',
      name: 'Debt of the Seas',
      cost: 'None',
      targetType: 'Passive',
      description: 'Có thể nợ AP để dùng kỹ năng, tối đa nợ là 10 AP (-10 AP). Trả hết nợ (AP >= 0) mới có thể dùng kỹ năng tiếp theo. AP từ việc ăn quân tự động trừ vào nợ.',
      duration: 'Permanent',
    },
    skill1: {
      id: 'pirate_bet',
      name: 'Bet',
      cost: APCostConfig.pirate.pirate_skill_1,
      targetType: 'Global Guess',
      description: 'Đánh cược đối phương sẽ dùng kỹ năng trong 2 vòng đấu tới (4 lượt). Nếu đúng được +8 AP, sai không có gì xảy ra.',
      duration: '4 turns',
    },
    skill2: {
      id: 'pirate_sailing',
      name: 'Sailing',
      cost: APCostConfig.pirate.pirate_skill_2,
      targetType: 'Ally & Target Tile',
      description: 'Trao hiệu ứng Sailing cho 1 quân đồng minh (trừ Vua) và chọn 1 ô trống. Quân đó bị trói chân trong 2 vòng (4 lượt), sau đó tự động bay tới ô đích. Nếu ô đích có địch thì ăn quân, đồng minh thì đứng yên.',
      duration: '4 turns',
    },
    ultimate: {
      id: 'pirate_broadside',
      name: 'Broadside',
      cost: APCostConfig.pirate.pirate_ultimate,
      targetType: 'Global Rooks',
      description: 'Khai hỏa toàn bộ quân Rook đồng minh trên bàn cờ ăn quân địch đầu tiên trên cùng cột phía trước mà không di chuyển. Vị trí quân bị ăn sẽ phát nổ 3x3 tiêu diệt toàn bộ quân địch xung quanh.',
      duration: 'Instant',
    }
  }
];

export function getVariantImageSrc(variantId: string | null | undefined): string {
  if (!variantId) return '/assets/variants/unknown.png';
  const variant = VARIANTS_LIST.find(v => v.id === variantId);
  const name = variant?.image || variantId;
  return `/assets/variants/${name}.png`;
}
